### ISSUE TITLE
Code documentation issue; Count cannot be less than zero

### ISSUE THREAD

**Issue by deap82** [statiqdev/Docable#13]
Hi again,
After pointing the SourceFiles setting to the right folder I'm getting the "api" generation running,
but when it runs I'm getting lots of errors like these ones;
![image](https://user-images.githubusercontent.com/1295067/157532210-6a4123be-ff86-4733-b73b-406ac1fb3b23.png)

The code base is quite large, and it seems the error is thrown for pretty much every class. Due to all these errors it's taking too long time to try to even finish the generation.

I tried to point the source files back to the statiq project itself, and that gives me a successful docs generation of the .cs files within the docable theme.

I'm really not sure what it is in my codebase that would cause these errors...

**Comment by daveaglick** [comment]
> I'm really not sure what it is in my codebase that would cause these errors...

I'm pretty sure you're hitting this issue: https://github.com/statiqdev/Statiq.Docs/issues/47

It's my highest priority now that everything is out, so I'll hopefully have a fix released in the next few days. I'll circle back here when I do and let you know.

**Comment by daveaglick** [comment]
This is now fixed and I'll do a release tomorrow to get it out. Be on the lookout for the next version!
