### ISSUE TITLE
Make <link> elements configurable

### ISSUE THREAD

**Issue by pascalberger** [statiqdev/Docable#24]
Currently there are a bunch of links hardcoded in the `_Layout.cshtml` page which require the corresponding files to be provided by the actual site. 

```
        <link rel="apple-touch-icon" sizes="180x180" href="@Context.GetLink("/assets/favicons/apple-touch-icon.png")">
        <link rel="icon" type="image/png" sizes="32x32" href="@Context.GetLink("/assets/favicons/favicon-32x32.png")">
        <link rel="icon" type="image/png" sizes="16x16" href="@Context.GetLink("/assets/favicons/favicon-16x16.png")">
        <link rel="manifest" href="@Context.GetLink("/assets/favicons/site.webmanifest")">
        <link rel="shortcut icon" type="image/png" href="@Context.GetLink("/assets/favicons/favicon.ico")"/>
        <link rel="mask-icon" href="@Context.GetLink("/assets/favicons/safari-pinned-tab.svg")" color="#e9ecef">
```

It would be nice if it can be configured which links should be added, so that only links can be added which are needed by the page, without copying whole `_Layout.cshtml`.

**Comment by daveaglick** [comment]
This is already supported via an override file in `/input/Shared/_Head.cshtml` (the version in Docable is totally empty, so it's designed to be overridden and provide stuff like this). That said, we had these favicons assets in the master layout that aren't actually part of the theme, so I've removed that as well and the expectation is that the user should now place this block (or any other favicon related content) in their own `/input/Shared/_Head.cshtml` file.
