### ISSUE TITLE
Blog and navigation issue

### ISSUE THREAD

**Issue by deap82** [statiqdev/Docable#3]
Hey, it's me again (from the Samson repo) :-)

As I understand it this is the theme to use once Statiq.Docs is ready to generate documentation from C# xml comments?

1. Blog?
I now have a site where I can navigate my structure of markdown input files, but in my Wyam site I also have the blog (entered via link in the top level navigation). Can I achieve that here (preferrably without building another site with the CleanBlog theme...)?

2. Navigation issue
Also, I have this input structure:
![image](https://user-images.githubusercontent.com/1295067/156797890-0c059e30-ba52-4826-b2d0-6e13a1ee1073.png)

But for the "backend" folder both "Backend" and "Architecture" comes out in top navigation. The top level files under infrastructure does not show in top navigation. I have no files where ShowInNavigation is set to false.

![image](https://user-images.githubusercontent.com/1295067/156798103-77315e28-e58d-45d6-bb2d-a0dda64d6c64.png)

Why is "Architecture" rendered in top navigation?

**Comment by daveaglick** [comment]
> I now have a site where I can navigate my structure of markdown input files, but in my Wyam site I also have the blog

A blog isn't directly supported by Docable yet (though it's certainly something I'll add eventually - there's a lot of little features like that, searching, anchor linking, code block copying, etc. that still need work - guess I should add some issues for those).

That said, Statiq is flexible enough that adding it yourself is pretty trivial using the [archives](https://www.statiq.dev/web/content-and-data/archives) feature. When you get right down to it, [this one file from CleanBlog](https://github.com/statiqdev/CleanBlog/blob/main/input/posts.cshtml) is doing most of the heavy lifting. That looks like a folder you tell it, finds all the posts, and then generates pages of them. You can add other features like tag-based archives by borrowing other files from CleanBlog until a blog is directly in Docable. Granted, they might need a little tweaking (I.e. the CleanBlog archive references some settings that you won't have in Docable like "PostSources").

Alternatively, now that you know it's in the plans, you could move forward and back-burner the blog bits until they officially land in Docable.

> But for the "backend" folder both "Backend" and "Architecture" comes out in top navigation. The top level files under infrastructure does not show in top navigation.

That's interesting, and might be a bug (?). Given the file layout I would have expected a "Backend" and "Infrastructure" item, not the "Architecture" one. Is there anything that might be "promoting" the `architecture.md` file to top-level (I.e. a child of the root index file)? Maybe a redirect or something that seems like it's that `architecture.md` file but is actually something else?

Here's the partial that generates that part of the navigation: https://github.com/statiqdev/Docable/blob/main/input/Shared/_RightNavigation.cshtml - I'd be curious to see what you get if you overwrite that by adding it in the same `/Shared/_RightNavigation.cshtml` path to your own input directory and have it output the full source path of each file so we can see where these are coming from.

**Comment by daveaglick** [comment]
I went ahead and opened #4 to track blogging support.

**Comment by deap82** [comment]
My apologies, it turned out I hade a copy of the architecture.md file in my root input folder, probably from playing around before I started to add in the input folders from my wyam site.

**Comment by daveaglick** [comment]
Oh good - glad this one wasn't something strange! And thanks a lot for opening those other issues, keep them coming :)
